NAME=principal

#
OBJECTS = $(NAME).o Vertice2D.o 

#
CPPFLAGS = -c -g -Wall -ansi -O2

INCLUDES = Vertice2D.hpp Vertice2DInterfaz.hpp

# Macros predefinidas
#
# $@: nombre del objetivo
# $^: todas las dependencias
# $<: primera dependencia
#

objetivo: $(NAME).exe

#Opciones para NO depurar los asertos
ndebug: CPPFLAGS += -DNDEBUG 
ndebug: objetivo

# Primer objetivo 
$(NAME).exe: $(OBJECTS)
			@echo "Generando " $@
			@g++ $^ -o $@
#
$(NAME).o: $(NAME).cpp $(INCLUDES)
			@echo "Compilando " $<
			@g++ $(CPPFLAGS) $<


#
Vertice2D.o: Vertice2D.cpp Vertice2D.hpp
			@echo "Compilando " $<
			@g++ $(CPPFLAGS) $<


# Generación de la documentación
doc: Doxyfile 
	@echo "Generando la documentación con doxygen"
	@doxygen
  
# Borrado
.PHONY: clean  
clean:
	@echo "Borrando los ficheros superfluos"
	@rm -f $(OBJECTS) *~ 

